kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: datastax-storage
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "1"
  priority_io: "high"
  group: "datastax_vg"
  fg: "true"
