apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: dc2
spec:
  serviceName: "datastax"
  replicas: 1
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dc2
    spec:
      securityContext:
        fsGroup: 999
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - dc2
            topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 7200
      containers:
      - name: datastax
        image: datastax/dse-server
        resources:
          requests:
            cpu: "0"
            memory: "128Mi"
        lifecycle:
          preStop:
            exec:
              command: 
              - /opt/dse/bin/nodetool
              - decommission
              - -f
        env:
        - name: DS_LICENSE
          value: accept
        - name: SEEDS
          value: datastax-0.datastax.default.svc.cluster.local
        - name: CLUSTER_NAME
          value: "K8s Test Cluster"
        - name: NUM_TOKENS
          value: "8"
        - name: DC
          value: "DC-2"
        - name: RACK
          value: "rack-1"
        - name: DSE_DATA
          value: datastax-storage
        - name: OPSCENTER_IP
          value: opscenter-0.opscenter.default.svc.cluster.local
        ports:
        - containerPort: 7000
          name: intra-node-port
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx-port
        - containerPort: 8609
          name: inter-node-msg
        - containerPort: 9042
          name: cql-port
        - containerPort: 9160
          name: thrift-port
        - containerPort: 8983
          name: solr-port
        - containerPort: 8984
          name: solr-int-node
        - containerPort: 4040
          name: spark-app-port
        - containerPort: 7077
          name: spark-int-node
        - containerPort: 7080
          name: spark-m-web
        - containerPort: 7081
          name: spark-w-web
        - containerPort: 8090
          name: spark-job
        - containerPort: 9999
          name: spark-job-jmx
        - containerPort: 18080
          name: spark-histor
        - containerPort: 8182
          name: gremlin-port
        - containerPort: 5598
          name: dsefs-public
        - containerPort: 5599
          name: dsefs-private
        - containerPort: 61621
          name: ds-agent-port
        volumeMounts:
        - name: datastax-local-claim
          mountPath: /var/lib/cassandra
        livenessProbe:
          tcpSocket:
            port: 9042
          initialDelaySeconds: 900
          timeoutSeconds: 1
          periodSeconds: 30
          failureThreshold: 10
  volumeClaimTemplates:
   - metadata:
       name: datastax-local-claim
     spec:
       accessModes:
       - ReadWriteOnce
       storageClassName: datastax-storage
       resources:
         requests:
           storage: 10Gi
